# Generated by Django 3.2 on 2025-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_remove_jobs_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('familyname', models.CharField(max_length=150)),
                ('Special', models.CharField(max_length=150)),
                ('resume', models.CharField(max_length=150)),
                ('jobs', models.ManyToManyField(to='jobs.Jobs')),
            ],
        ),
    ]
