# Generated by Django 3.2 on 2025-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
