# Generated by Django 3.2 on 2025-05-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='users',
        ),
    ]
